language: java
before_install:
  - git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.8
  - . $HOME/.asdf/asdf.sh
install:
  - asdf plugin add nodejs
  - asdf plugin add yarn
  - asdf install nodejs 13.14.0
  - asdf install yarn 1.22.4
script:
  - asdf --version
  - node --version
  - yarn --version
